# Generated by Django 6.0.3 on 2026-03-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_fiado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiado',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
